obj-y :=	ifxos_version.o				\
		ifxos_debug.o				\
		ifx_fifo.o				\
		ifxos_linux_module_drv.o		\
		ifxos_linux_copy_user_space_drv.o	\
		ifxos_linux_memory_map_drv.o	

obj-$(CONFIG_LANTIQ_IFXOS_EVENT)	+= ifxos_linux_event_drv.o
obj-$(CONFIG_LANTIQ_IFXOS_LOCK)	        += ifxos_linux_lock_drv.o
obj-$(CONFIG_LANTIQ_IFXOS_MEMORY)	+= ifxos_linux_memory_alloc_drv.o
obj-$(CONFIG_LANTIQ_IFXOS_MUTEX)	+= ifxos_linux_mutex_drv.o
obj-$(CONFIG_LANTIQ_IFXOS_SELECT)	+= ifxos_linux_select_drv.o
obj-$(CONFIG_LANTIQ_IFXOS_SOCKET)	+= ifxos_linux_socket_drv.o
obj-$(CONFIG_LANTIQ_IFXOS_THREAD)       += ifxos_linux_thread_drv.o
obj-$(CONFIG_LANTIQ_IFXOS_TIME)	        += ifxos_linux_time_drv.o
