obj-y := prom.o sysctrl.o clk.o reset.o dma.o gptu.o dcdc.o

obj-y += vmmc.o

obj-y += eth_mac.o
obj-$(CONFIG_PCI) += ath_eep.o rt_eep.o pci-ath-fixup.o

obj-$(CONFIG_XRX200_PHY_FW) += xrx200_phy_fw.o
